import type { NextPage } from "next";
import Head from "next/head";
import "@markmiro/css-base";
import styles from "../styles/Home.module.css";
import { Choice, ChoiceType } from "../components/choice";
import { faker } from "@faker-js/faker";
import { useState } from "react";

faker.seed(1);

function createChoice(): ChoiceType {
  return {
    id: faker.random.alphaNumeric(10),
    img: "https://picsum.photos/80",
    color: faker.color.hsl(),
    name: faker.lorem.word(),
    children: [],
  };
}

function createChoices(count: number) {
  const arr = new Array(count);
  for (let i = 0; i < arr.length; i++) {
    arr[i] = createChoice();
  }
  return arr;
}

const choices = createChoices(5);

const Home: NextPage = () => {
  const choiceState = useState<string>("");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Glide Choice Component</h1>
        <a href="https://www.figma.com/file/gXlpBINSgg129W887h5ygW/Choice-Component?node-id=0%3A1">
          Figma File
        </a>
      </main>
      <Choice choices={choices} state={choiceState} />
    </div>
  );
};

export default Home;
